virt/taller/taller/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tallermecanico.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

virt/taller/tallermecanico/urls.py
from django.urls import path
from . import views
from .views import register
from django.contrib import admin

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('appointment/', views.appointment, name='appointment'), 
    path('register/', register, name='register'),
    path('admin/', admin.site.urls),
    
]

virt/taller/tallermecanico/models.py
from django.db import models
import datetime

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'categories'
    
class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return '{self.first_name} {self.last_name}'

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    description = models.CharField(max_length=250, default='', blank=True, null=True),
    image = models.ImageField(upload_to='upload/product/')

    is_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0, decimal_places=2, max_digits=6)

    def __str__(self):
        return self.name
    


class Appointment(models.Model):
    visitor_name = models.CharField(max_length=100)
    visitor_email = models.EmailField()
    visitor_phone = models.CharField(max_length=20)
    checkin = models.DateField()
    checkout = models.DateField()
    visitor_message = models.TextField()

virt/taller/tallermecanico/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Appointment
from django.contrib.auth.models import User 

class AppointmentForm(forms.Form):
    visitor_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    visitor_email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    visitor_phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    checkin = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
    checkout = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
    visitor_message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))



class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'



class RegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

virt/taller/tallermecanico/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from .models import Product
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import AppointmentForm
from .forms import RegisterForm


# Create your views here.
def home(request):
    products = Product.objects.all()
    return render(request, 'home.html', {'products': products})

def about(request):
    return render(request, 'about.html', {})

def login_user(request):
    if request.method == "POST":
        username =request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ("¡Has entrado a tu cuenta!"))
            return redirect('home')
        else: 
            messages.succes(request, ("Hubo un error, por favor intenta nuevamente"))
            return redirect('login')
        
    else:
        return render(request, 'login.html', {})

def logout_user(request):
    logout(request)
    messages.success(request, ("¡Has cerrado sesión, gracias por visitar! "))
    return redirect('home')

    
def appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  # Redirect to a success page
    else:
        form = AppointmentForm()
    return render(request, 'appointment.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  # Replace 'home' with the URL name of your home page
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})

virt/taller/tallermecanico/templates/about.html
{% extends 'base.html' %}

{% block content %}

    <header class="bg-dark py-2">
        <div class="container px-2 px-lg-3 my-3">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Quiénes somos...</h1>
                <p class="lead fw-normal text-white-50 mb-0">Atendemos en Antonio Varas 666</p>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <center>
                <div class="col-8">
                    <br>
                    <br>
                    <p align="justify">Crecemos con tu interés, vendemos productos, ven a visitarnos, atendemos muy bien en nuestro taller
                        <br>
                        Contacte con nuestro equipo de ventas para definir cuál es la batería adecuada para su vehículo, coordine con ellos el día y hora de instalación y listo!.
Llámanos al:
+(32) 213 2720
(32) 213 2720

Horarios de Atención:
De lunes a viernes de 8:30 am a 7:00 pm
Sabados de 9:00 am a 3:00 pm
Domingos cerrados
<br>
Nos ajustamos a tu horario
Nos ajustamos a la hora de recepción y entrega de su auto fuera de los horarios establecidos con previa cita.
Paga desde la comididad de tu casa
                    </p>
                    <br>
                    <br>
                    <br><br>
                </div>
            </center>
        </div>
    </div>
    



{% endblock %}

virt/taller/tallermecanico/templates/appointment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <form action="{% url 'appointment' %}" method="post">
        {% csrf_token %}
        <!-- Form fields here -->
        <div class="form-group">Nombre</label>
            <input type="text" class="form-control" id="id_visitor_name" name="visitor_name">
        </div>
        <div class="form-group">
            <label for="id_visitor_email">Email</label>
            <input type="email" class="form-control" id="id_visitor_email" name="visitor_email">
        </div>
        <div class="form-group">
            <label for="id_visitor_phone">Celular</label>
            <input type="text" class="form-control" id="id_visitor_phone" name="visitor_phone">
        </div>
        <div class="form-group">
            <label for="id_checkin">Día de entrada</label>
            <input type="date" class="form-control" id="id_checkin" name="checkin">
        </div>
        <div class="form-group">
            <label for="id_checkout">Día de salida</label>
            <input type="date" class="form-control" id="id_checkout" name="checkout">
        </div>
        <div class="form-group">
            <label for="id_visitor_message">Mensaje</label>
            <textarea class="form-control" id="id_visitor_message" name="visitor_message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary" onclick="redirectToHome()">Reserva</button>

<script>
function redirectToHome() {
    window.location.href = "home.html";
}
</script>
        <br>
    </form>
    <br>
</div>
<br>
<br>

<!-- Include Bootstrap CSS and JavaScript files -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

{% endblock %}

virt/taller/tallermecanico/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Automatizate.cl - Taller mecánico</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'navbar.html'%}
        {% if messages %}
            {% for messages in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <strong>Bienvenido(a)!</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock %}


        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Taller mecánico 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>

virt/taller/tallermecanico/templates/home.html
{% extends 'base.html' %}

        {% block content %}
<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Taller mecánico</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Automatizate</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                    {% for product in products %}
                    <div class="col mb-5">
                        
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Impresionantes ofertas</h5>
                                    <!-- Product price-->
                                    $40.00 - $80.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Ver opciones</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor%}

                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock %}

virt/taller/tallermecanico/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <header class="bg-dark py-2">
        <div class="container px-2 px-lg-3 my-3">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Quiénes somos...</h1>
                <p class="lead fw-normal text-white-50 mb-0">Atendemos en Antonio Varas 666</p>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <center>
                <div class="col-8">
                    
                <br>
                <br>
                <br>
                <br>
                <form method="POST" action="{% url 'login' %}">
                    <h2 class="mb-4">Inicia sesión</h2>
            
                    {% csrf_token %}
                    <div class="mb-3">
                      <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
                    </div>
                    <br>
                    <br>
                    <div class="mb-3">
                      <input type="password" class="form-control" name="password" placeholder="Ingresa tu contraseña"</input>
                      <br>
                      
                    </div>
                    <button type="submit" class="btn btn-secondary">Entrar</button>
                  </form>
                  <br>
                  <br>
                  <br>
                  <br>
                
                </div>
            </center>
        </div>
    </div>


    



{% endblock %}

virt/taller/tallermecanico/templates/navBar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">Comienza con nosotros</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Sobre nosotros</a></li>

                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'appointment' %}">Agenda una hora</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Salir</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Entrar</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

virt/taller/tallermecanico/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form method="POST" novalidate>
        {% csrf_token %}
        <h2 class="mb-4">Registrate</h2>

        {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
          <div class="alert alert-danger">
            {% for error in field.errors %}
            <p class="mb-0">{{ error }}</p>
            {% endfor %}
          </div>
          {% endif %}
          {{ field.label_tag }}
          {{ field }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Registrarse</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}